apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzYW5keWtyLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBUYUdGeWJXRXpNeUVoIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
